--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.5.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10-Jan-24 22:34:35
-- Server version: 10.4.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE tunetracer;

--
-- Drop table `ajanlasok`
--
DROP TABLE IF EXISTS ajanlasok;

--
-- Drop table `playlists`
--
DROP TABLE IF EXISTS playlists;

--
-- Drop table `subscriptions`
--
DROP TABLE IF EXISTS subscriptions;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `playlistnames`
--
DROP TABLE IF EXISTS playlistnames;

--
-- Drop table `audio`
--
DROP TABLE IF EXISTS audio;

--
-- Drop table `artist`
--
DROP TABLE IF EXISTS artist;

--
-- Set default database
--
USE tunetracer;

--
-- Create table `artist`
--
CREATE TABLE artist (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Description TEXT DEFAULT NULL,
  profile_img MEDIUMBLOB DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 40960,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create table `audio`
--
CREATE TABLE audio (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) DEFAULT NULL,
  Author INT(11) DEFAULT NULL,
  filename VARCHAR(255) DEFAULT NULL,
  cover_art_file MEDIUMBLOB DEFAULT NULL,
  isAd TINYINT(1) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 1851392,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE audio 
  ADD CONSTRAINT FK_audio_Author FOREIGN KEY (Author)
    REFERENCES artist(ID) ON DELETE NO ACTION;

--
-- Create table `playlistnames`
--
CREATE TABLE playlistnames (
  ID INT(11) NOT NULL,
  Name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Username VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(50) DEFAULT NULL,
  RealName VARCHAR(255) DEFAULT NULL,
  BDay DATE DEFAULT NULL,
  Password VARCHAR(255) DEFAULT NULL,
  isAdmin TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 38,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create table `subscriptions`
--
CREATE TABLE subscriptions (
  ID INT(11) DEFAULT NULL,
  Price FLOAT DEFAULT NULL,
  RenewalDate DATE DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE subscriptions 
  ADD CONSTRAINT FK_Subscriptions_ID FOREIGN KEY (ID)
    REFERENCES users(ID) ON DELETE NO ACTION;

--
-- Create table `playlists`
--
CREATE TABLE playlists (
  SongID INT(11) DEFAULT NULL,
  UserID INT(11) DEFAULT NULL,
  PlaylistID INT(11) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE playlists 
  ADD CONSTRAINT FK_Playlists_PlaylistID FOREIGN KEY (PlaylistID)
    REFERENCES playlistnames(ID) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE playlists 
  ADD CONSTRAINT FK_Playlists_SongID FOREIGN KEY (SongID)
    REFERENCES audio(ID) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE playlists 
  ADD CONSTRAINT FK_Playlists_UserID FOREIGN KEY (UserID)
    REFERENCES users(ID) ON DELETE NO ACTION;

--
-- Create table `ajanlasok`
--
CREATE TABLE ajanlasok (
  SongID INT(11) DEFAULT NULL,
  UserID INT(11) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE ajanlasok 
  ADD CONSTRAINT FK_ajanlasok_SongID FOREIGN KEY (SongID)
    REFERENCES audio(ID) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE ajanlasok 
  ADD CONSTRAINT FK_ajanlasok_UserID FOREIGN KEY (UserID)
    REFERENCES users(ID) ON DELETE NO ACTION;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;